build_stable:
  image: docker:git
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/skhu-sss/skhufeeds:latest skhufeeds
    - docker push registry.gitlab.com/skhu-sss/skhufeeds:latest
  only:
    - master

build_unstable:
  image: docker:git
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/skhu-sss/skhufeeds:unstable skhufeeds
    - docker push registry.gitlab.com/skhu-sss/skhufeeds:unstable
  only:
    - unstable
