# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('title', models.CharField(max_length=45)),
                ('summary', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('desc', models.TextField()),
                ('phone', models.CharField(max_length=45)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('source_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('url', models.URLField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='newsfeed',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crawlers.Source'),
        ),
    ]
