# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Phone',
            new_name='Contact',
        ),
    ]
