# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 06:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_alter_user_username_max_length'),
        ('crawlers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscribeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawlers.Sources')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_pull', models.DateTimeField()),
                ('token', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='subscribelist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
