# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_auto_20170727_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last_command',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
