# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_userinfo_last_command'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='secret',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='token',
            field=models.TextField(null=True),
        ),
    ]
