# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_auto_20170731_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='last_command',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='secret',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='token',
            field=models.TextField(default=''),
        ),
    ]
