# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_auto_20170731_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='token',
            new_name='jwt_token',
        ),
    ]
